---
server:
  port: 10000
spring:
  application:
    name: eureka-server
  profiles: peer1
  security:
    user:
      name: wen
      password: qiyu
# 将peer1注册到peer2，peer3
eureka:
  instance:
    hostname: peer1
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://wen:qiyu@peer2:10001/eureka/,http://wen:qiyu@peer3:10002/eureka/
---
server:
  port: 10001
spring:
  application:
    name: eureka-server
  profiles: peer2
  security:
    user:
      name: wen
      password: qiyu
# 将peer2注册到peer1，peer3
eureka:
  client:
    service-url:
      defaultZone: http://wen:qiyu@peer1:10000/eureka/,http://wen:qiyu@peer3:10002/eureka/
  instance:
    hostname: peer2
---
server:
  port: 10002
spring:
  application:
    name: eureka-server
  profiles: peer3
  security:
    user:
      name: wen
      password: qiyu
# 将peer3注册到peer1，peer2
eureka:
  client:
    service-url:
      defaultZone: http://wen:qiyu@peer1:10000/eureka/,http://wen:qiyu@peer2:10001/eureka/
  instance:
    hostname: peer3
# 打包方式运行
#java -jar eureka-server.jar --spring.profiles.active=peer1
#java -jar eureka-server.jar --spring.profiles.active=peer2
#java -jar eureka-server.jar --spring.profiles.active=peer3